"""Add subroles and cv pdf

Revision ID: 5e8f4ae2f5b2
Revises: 651ce11748f8
Create Date: 2026-10-08 14:14:01.457637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8f4ae2f5b2'
down_revision: Union[str, Sequence[str], None] = '651ce11748f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('pdf_file_path', sa.String(), nullable=True))
    op.execute("ALTER TYPE roleenum ADD VALUE IF NOT EXISTS 'super_admin'")
    op.execute("ALTER TYPE roleenum ADD VALUE IF NOT EXISTS 'faculty_coordinator'")
    op.execute("ALTER TYPE roleenum ADD VALUE IF NOT EXISTS 'student_representative'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cvs', 'pdf_file_path')
    # ### end Alembic commands ###
