"""add_feedback_table

Revision ID: 651ce11748f8
Revises: fb656e21ffd0
Create Date: 2026-09-12 19:46:53.989075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651ce11748f8'
down_revision: Union[str, Sequence[str], None] = 'fb656e21ffd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_type', sa.Enum('student', 'company', name='authortypeenum'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('company', 'student', 'interview', 'job', name='targettypeenum'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
